fix: metadata can't be created on Windows
Fixes issue #1882:
WorkflowError: Metadata can't be created as it already exists (Windows)

Cause: os.rename fails with an exception on Windows if the target exists
Fix: os.replace is a cross-platform way to achieve the same
(cf. https://stackoverflow.com/q/8107352)