fix: convert parameters so they can be serialized (#2925)
<!--Add a description of your PR here-->

Some parameter types (e.g. `Path` or `np`) are not serializable when
requesting extended benchmarks (and maybe in other other places #1425):

```bash
$ snakemake test.out -j 1 --benchmark-extended -F
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count
-----  -------
1            1
total        1

Select jobs to execute...
Execute 1 jobs...

[Thu Jul 11 11:07:47 2024]
localrule 1:
    output: test.out
    jobid: 0
    benchmark: test.jsonl
    reason: Forced execution
    resources: tmpdir=/tmp

WorkflowError:
TypeError: Object of type int64 is not JSON serializable
[Thu Jul 11 11:07:50 2024]
Error in rule 1:
    jobid: 0
    output: test.out

Exiting because a job execution failed. Look above for error message
WorkflowError:
At least one job did not complete successfully.
[Thu Jul 11 11:07:50 2024]
Error in rule 1:
    jobid: 0
    output: test.out

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-07-11T110746.832532.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

Not sure why, but the tests all pass! :confused: 


### QC
<!-- Make sure that you can tick the boxes below. -->

* [x] The PR contains a test case for the changes or the changes are
already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or
this is not necessary (e.g. if the change does neither modify the
language nor the behavior or functionalities of Snakemake).


<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

- **New Features**
- Added new parameters for testing: `path` and `np` to enhance test
configurations.
- Introduced performance benchmarking for the `test_nonstr_params`
function.

- **Bug Fixes**
- Updated the test to skip on Windows platforms, addressing
compatibility issues.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

---------

Co-authored-by: Johannes Köster <johannes.koester@tu-dortmund.de>