Win notebook support (#1034)
* Change conda tests so they can run on Windows

This changes the BWA commandline tool used in the tests to an
other small small command line tool called 'melt'.

 It makes the test a bit slower since the 'melt' tool  also depends
 on Python. But I couldn't find a small cross platform tool on
 bioconda which could be used for the tests.

* Wrap urlparse in a version which also works on Windows

It seems like snakemake uses urlparse to distinguish between URI's and
paths.

That 'undocumented' feature doesn't work with windows paths. So here
we wrap urlparse in snakemake.utils and add some code which adds this
'feature' for windows paths.

* Only use argvquote on Win when cmd.exe is the shell

This changes utils.format function a bit by exposing the  quote_func
arguments of QuotedFormatter.

* Add test for conda when using cmd.exe as shell

* Fix various issues with conda support on Win

* New black version

* Ignore errors in cleanup when testing on CI server

On windows we got :
PermissionError: [WinError 5] Access is denied: 'C:\\...\\vcruntime140.dll

* Use smart_open instead of urllib's urlparse

* Fail gracefully when a scheme is not implemented by smart_open

* Fix problems with Notebook on Windows

* Enable test which now works on Win

* Update notebook.py

Co-authored-by: Johannes Köster <johannes.koester@uni-due.de>
Co-authored-by: Johannes Köster <johannes.koester@uk-essen.de>