Merged in giesselmann/snakemake/threads_in_resource_lambda (pull request #354)
Add thread argument to resource lambda function calls

Related to comment in issue 279:
TypeError: <lambda>() missing 1 required positional argument: 'threads'