ci: bump pixi version in actions (#3903)
Pixi install github action is failing with "failed to parse pypi name
mapping" errors likely due to rate limiting when 30+ jobs are kicked off
nearly simultaneously

I tested this fix on #3820 since the tests kept failing due to the
`pixi` install action failing. After committing this change, [the
actions ran
successfully](https://github.com/snakemake/snakemake/actions/runs/20684893321).

In [this failing
run's](https://github.com/snakemake/snakemake/actions/runs/20682879051/job/59383597583#step:3:3261)
debug logs we see:
```
pixi install -e py311
[...]
   WARN resolve_conda{group=py313 platform=win-64}: reqwest_retry::middleware: Retry attempt #1. Sleeping 1.225245051s before the next attempt
  Error:   × failed to parse pypi name mapping
    ├─▶ error decoding response body
    ╰─▶ expected value at line 1 column 1
```
This warning is repeated many times until finally pixi stops retrying -
this is what suggested to me that some sort of rate limit was the issue.


One downside is that this does make the CI take a bit longer to run. We
could consider using the `cache` feature of the pixi action. And turning
up the max-parallel, or reducing the number of test-groups


### QC
<!-- Make sure that you can tick the boxes below. -->

* [ ] The PR contains a test case for the changes or the changes are
already covered by an existing test case.
* [ ] The documentation (`docs/`) is updated to reflect the changes or
this is not necessary (e.g. if the change does neither modify the
language nor the behavior or functionalities of Snakemake).



<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

* **Chores**
* Updated development toolchain dependencies for improved build and test
infrastructure.

<sub>✏️ Tip: You can customize this high-level summary in your review
settings.</sub>

<!-- end of auto-generated comment: release notes by coderabbit.ai -->