fix: more robust parsing of sacct output in slurm executor (#2036)
Fix error in parse jobid and jobidraw. jobid and jobidraw might be
different.

### Description

--slurm command report such error:

```
  File "~/.local/lib/python3.11/site-packages/snakemake/executors/slurm/slurm_submit.py", line 328, in job_status
    return res[jobid]  # == status
           ~~~^^^^^^^
KeyError: '1043166'
```

This is because sacct command report JobId but not JobIdRaw in the first
column, which cause error in indexing the job status in the res dict.
For example,

```
$ sacct -P -n --format=JobId,JobIdRaw,State -j 1043166

1043074_91|1043166|COMPLETED
1043074_91.batch|1043166.batch|COMPLETED
1043074_91.extern|1043166.extern|COMPLETED
1043074_91.0|1043166.0|COMPLETED
```

replacing `-b` with `--format=JobIdRaw,State` can have a more robust
output.

Co-authored-by: Johannes Köster <johannes.koester@tu-dortmund.de>