make sudo apt install stably choose the best mirror
This should make this step stable against otherwise randomly recurring trouble with the azure mirror. The solution is given and explained here:
https://github.com/actions/runner-images/issues/675#issuecomment-1419388451

Basically, this looks for the best mirror in US, where GitHub Actions seems to be hosted, and then updates to get the latest index from there.

Hopefully, this consistently avoids failures like this one in the future:
https://github.com/snakemake/snakemake/actions/runs/4291216092/jobs/7478626266#step:13:112

```
sudo apt install -y stress git wget openmpi-bin libopenmpi-dev mariadb-server
[...]
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 mariadb-common all 1:10.6.11-0ubuntu0.22.04.1
  404  Not Found [IP: 40.81.13.82 80]
Err:5 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libmariadb3 amd64 1:10.6.11-0ubuntu0.22.04.1
  404  Not Found [IP: 40.81.13.82 80]
Err:6 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 mariadb-client-core-10.6 amd64 1:10.6.11-0ubuntu0.22.04.1
  404  Not Found [IP: 40.81.13.82 80]
Err:7 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 mariadb-client-10.6 amd64 1:10.6.11-0ubuntu0.22.04.1
  404  Not Found [IP: 40.81.13.82 80]
Err:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 mariadb-server-core-10.6 amd64 1:10.6.11-0ubuntu0.22.04.1
  404  Not Found [IP: 40.81.13.82 80]
Err:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 mariadb-server-10.6 amd64 1:10.6.11-0ubuntu0.22.04.1
  404  Not Found [IP: 40.81.13.82 80]
Err:41 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 mariadb-server all 1:10.6.11-0ubuntu0.22.04.1
  404  Not Found [IP: 40.81.13.82 80]
Fetched 12.2 MB in 12s (985 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.6/mariadb-common_10.6.11-0ubuntu0.22.04.1_all.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.6/libmariadb3_10.6.11-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.6/mariadb-client-core-10.6_10.6.11-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.6/mariadb-client-10.6_10.6.11-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.6/mariadb-server-core-10.6_10.6.11-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.6/mariadb-server-10.6_10.6.11-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mariadb-10.6/mariadb-server_10.6.11-0ubuntu0.22.04.1_all.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```