fix: is_run error with local, group jobs (#2133)
### Description

Ran into a bug where executing a workflow locally causes a crash with
group jobs.
```
    if self.workflow.verbose or (job.is_run and not job.is_group()):
                                 ^^^^^^^^^^
AttributeError: 'GroupJob' object has no attribute 'is_run'
```
Swapping the order of the checks fixes this issue; not sure why the CI
didn't catch this bug.